### ISSUE TITLE
Angor Indexer Offline on Initial Load

### ISSUE THREAD

**Issue by itailiors** [block-core/angor#110]
Issue Summary:
The Angor indexer is offline when loading Angor for the first time. The system does not reconnect the indexer over time. 
Going to browse tab results in an error due to the offline indexer. 
Additionally there is no popup or failsafe to handle this error in browse, 
so i would suggest trying to catch the error in browse.

The issue requires refreshing manually in the settings to refresh the indexer.

Steps to Reproduce:

Run Angor on localhost.
Enter the application using incognito mode (to ensure no cache).
Press the "Browse" button.
see error in console

Actual:

On the first-time load, the indexer is offline.
Manual refresh of the indexer in settings is required.

Expected Behavior:

The indexer should be online on the first-time load.
There should be a popup or a failsafe mechanism to handle the offline indexer error.

error:
`blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: No indexer found go to settings to add an indexer.
System.ApplicationException: No indexer found go to settings to add an indexer.
   at Angor.Shared.Services.NetworkService.GetPrimaryIndexer() in C:\Users\Itay\GitHubReps\test\angor\src\Angor\Shared\Services\NetworkService.cs:line 162
   at Angor.Shared.Services.IndexerService.GetProjectsAsync(Nullable`1 offset, Int32 limit) in C:\Users\Itay\GitHubReps\test\angor\src\Angor\Shared\Services\IndexerService.cs:line 70
   at Angor.Client.Pages.Browse.GetAllProjects() in C:\Users\Itay\GitHubReps\test\angor\src\Angor\Client\Pages\Browse.razor:line 276
   at Angor.Client.Pages.Browse.OnInitializedAsync() in C:\Users\Itay\GitHubReps\test\angor\src\Angor\Client\Pages\Browse.razor:line 220
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync() `

**Comment by dangershony** [comment]
Very good spot indeed we need to handle offline indexer and relay handling
