### ISSUE TITLE
Issues Found in Angor

### ISSUE THREAD

**Issue by itailiors** [block-core/angor#98]
1. When you press "Copy nsec to clipboard" in the founder project, you get an error:

```
```blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_NullReferenceException
System.NullReferenceException: Arg_NullReferenceException
   at Angor.Client.Pages.View.CopyNsecToClipboardAsyncCheckPassword()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState  ) ```
```
2. When you navigate to the penalties section, there is no way back.
3. Whenever you have a project, the "Scan for founder projects" button disappears.
4. When creating a project, how do you add an image? Also, if you submit and get an error, trying to delete the field doesn't work. (I assume milad will change this in the future, so it's not a big deal for now.)
5. There should be an explanation for what penalties are, perhaps a tooltip?
6. The wallet page could be more user-friendly if it fit into a single page for easier navigation.

**Comment by itailiors** [comment]
@DavidGershony 
is number 3 associated with https://github.com/block-core/angor/issues/103 ?
(because of the additional scan)

**Comment by itailiors** [comment]
Issue number 2 and 3 can be linked to https://github.com/block-core/angor/issues/103 , 
All the other issues are fixed.
